-- ################################# GWR DEFINES #####################################
-- GAME
NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 999
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 999
NDefines.NGame.MESSAGE_TIMEOUT_DAYS = 14
NDefines.NGame.MAX_SCRIPTED_LOC_RECURSION = 1001			

-- FOCUS
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 30
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 30

-- ARMY
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999
NDefines.NMilitary.COHESION_IMMOBILE_PLANNING_SPEED_MULTIPLIER = 1
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 0
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 0
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 0

-- PRODUCTION
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 10
NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE  = 15
NDefines.NProduction.CONVOY_MAX_NAV_FACTORIES_PER_LINE  = 150
NDefines.NProduction.RAILWAY_GUN_MAX_MIL_FACTORIES_PER_LINE  = 10
NDefines.NProduction.ANNEX_CONVOYS_RATIO  = 0.35
NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST = 0
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 0
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 0
NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 0

-- AIR
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_NO_TRUCK_DISRUPTION_FACTOR = 0.0
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_TRUCK_DAMAGE_FACTOR = 0.0
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_TRAIN_DAMAGE_FACTOR = 0.0
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_INFRA_DAMAGE_SPILL_FACTOR = 0.0
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_TRUCK_MAX_FACTOR = 0.0
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_TRAIN_DAMAGE_DISRUPTION_MITIGATION = 0.0
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_DIRECT_DISRUPTION_DAMAGE_FACTOR = 0.0
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_RAILWAY_DAMAGE_SPILL_FACTOR = 0.0
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_MAX_DISRUPTION_DAMAGE_TO_CONSIDER = 0.0
NDefines.NAir.AIR_WING_ATTACK_LOGISTICS_DISRUPTION_MIN_DAMAGE_FACTOR = 0.0
NDefines.NAir.MIN_PLANE_COUNT_PARADROP = 100
NDefines.NAir.AA_INDUSTRY_AIR_DAMAGE_FACTOR = -0.125
NDefines.NAir.AIR_SUPPLY_CONVERSION_SCALE = 0.025
